### ISSUE TITLE
CocoaPods releases update

### ISSUE THREAD

**Issue by Peretz30** [webim/webim-client-sdk-ios#13]
I am using [WebimClientLibrary](https://cocoapods.org/pods/WebimClientLibrary) as dependency for a module in my project. So, I can't use this pod thought git url. I only can use it from CocoaPods. But your last release there published in 2018. Can you, please, release last version in Cocoapods and keep it up to date?

**Comment by MadGeorge** [comment]
three years later...

**Comment by webim** [comment]
New releases are published on [WebimMobileSDK](https://cocoapods.org/pods/WebimMobileSDK).

**Comment by MadGeorge** [comment]
Thanks for a 4-year late response
