### ISSUE TITLE
Не работает библиотека при установке Carthage на XCode 12.5

### ISSUE THREAD

**Issue by Raidar13rus** [webim/webim-client-sdk-ios#15]
Библиотека Webim-Client-sdk-ios не работает при установке через Carthage на xCode 12.5. При явном указании версии и без 
<a href="https://ibb.co/ctqs9Hh"><img src="https://i.ibb.co/BjkYJx2/2021-05-27-12-38-59-PM.png" alt="2021-05-27-12-38-59-PM" border="0"></a>

**Comment by webim** [comment]
Больше не актуально.
