### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by maslovsa** [webim/webim-client-sdk-ios#2]
`github "webim/webim-client-sdk-ios" ~> 3.7.0`

I added such line to my Carthage config.
And get that error -

`Dependency "webim-client-sdk-ios" has no shared framework schemes for any of the platforms: iOS`

Please make Framework scheme **Shared**.

Click on Project Name in Xcode - Manage Schemas
Check the image below ->

![alt text](https://cdn-images-1.medium.com/max/1600/1*FKIq94z8YJYursV8WuHgSw.png "Logo Title Text 1")

[More info](https://medium.com/@shenghuawu/support-carthage-for-your-swift-framework-f294c691f9ba)

PS Also you can write on Readme, that you support **Carthage** =)

**Comment by webim** [comment]
Hi!

Thanks for that tip!

We just added Carthage support in version 3.9.0.

You can add following line to your Cartfile:
github "webim/webim-client-sdk-ios" ~> 3.9.0

Have a nice holidays!

**Comment by webim** [comment]
Hi!

Thanks for that tip!

We just added Carthage support in version 3.9.0.

You can add following line to your Cartfile:
`github "webim/webim-client-sdk-ios" ~> 3.9.0`

Have a nice holidays!
