### ISSUE TITLE
Не отрабатывает тег версии и отсутсвует LocationSettingsResponse в 3.36.0

### ISSUE THREAD

**Issue by justnicke** [webim/webim-client-sdk-ios#20]
Добрый День! 
Сегодня столкнулись с проблемой, что при pod update, не срабатывает тег версии и обновляет до последней 3.36.0
в которой отсутсвует LocationSettingsResponse в классе MessageStreamImpl, строка 712.

Вчера до 3.36.0 релиза, отрабатывало все хорошо, возможно у вас что-то произошло.

**Comment by smallkot** [comment]
Здравствуйте. Уберите из описание параметр :branch=> 'master'. 
pod 'WebimClientLibrary', :git => 'https://github.com/webim/webim-client-sdk-ios.git', :branch => 'master', :tag => '3.33.0'

Правильно будет так:
pod 'WebimClientLibrary', :git => 'https://github.com/webim/webim-client-sdk-ios.git', :tag => '3.33.0'


если оставить  :branch то :tag игнорируется (

**Comment by webim** [comment]
Добрый день!
Попробуйте тег 3.36.1. Там поправили проблемы, которые были в 3.36.0.

UPD: в 3.36.1 обнаружена критическая ошибка, при обновлении с версии ниже 3.36.0 лучше использовать 3.36.2.

**Comment by webim** [comment]
В версии 3.36.2 убрали из README параметр :branch=> 'master'. Как было сказано выше, указание ветки игнорирует тег.
