### ISSUE TITLE
iOS 16 support

### ISSUE THREAD

**Issue by djarlaks** [webim/webim-client-sdk-ios#23]
Не собирается из-за SQLite на Xcode 14 beta с ошибкой 
`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`

Версия 3.37.0
Библиотека подключена через CocoaPods

**Comment by Wistas23** [comment]
Подтверждаю, в Xcode 14 beta 3 ошибка сохраняется.
Не зависит от версии библиотеки.
<img width="879" alt="image" src="https://user-images.githubusercontent.com/36187314/177622756-cc970be7-273a-4218-a26e-5a2e731b6513.png">

**Comment by NeboLej** [comment]
Подтверждаю xcode 14.0.1 чат 3.37.0 ошибка присутствует

**Comment by webim** [comment]
Ошибка исправлена в версии 3.37.1.
