### ISSUE TITLE
Support App Privacy Manifest

### ISSUE THREAD

**Issue by triolyami** [webim/webim-client-sdk-ios#25]
Планируется ли добавление Privacy Manifest в проект?
![image](https://github.com/webim/webim-client-sdk-ios/assets/101165361/0e88dd19-667d-443c-b51a-ca2040642e96)
Весной этого года апстор может перестать принимать приложения, в SDK которых отсутствуют заполненные манифесты
https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by webim** [comment]
Privacy Manifest добавлен в версии 3.41.5.
