### ISSUE TITLE
Sqlite на Xcode 16

### ISSUE THREAD

**Issue by AnastasiyaSachkova** [webim/webim-client-sdk-ios#27]
Невозможно собрать приложение на Xcode 16 так как WebimClientLibrary давно не обновлялось под новые требования Apple. 
А именно ошибка возникает при обращении к Sqlite в файле SQLiteHistoryStorage.
Прошу это исправить, дополнительно напишу в поддержку, так как подписка куплена, а сервисом пользоваться невозможно 
![Снимок экрана 2024-10-14 в 11 48 44](https://github.com/user-attachments/assets/6f741406-805c-4f41-a669-c1009e338a13)
![Снимок экрана 2024-10-14 в 11 49 11](https://github.com/user-attachments/assets/06a795e5-73ee-48b0-b068-3f85f3314f3a)

**Comment by webim** [comment]
Судя по скриншоту, в Podfile вы используете `WebimClientLibrary`. Некоторое время назад мы переименовали библиотеку в `WebimMobileSDK`, вам следует указывать в Podfile это название (в README это указано).
Поддержка Xcode 16 была добавлена в версии 3.41.9, актуальная версия на данный момент 3.42.0.

**Comment by AnastasiyaSachkova** [comment]
Помогло переименование либы, спасибо!
