### ISSUE TITLE
Have crash, when use your pod 

### ISSUE THREAD

**Issue by OberemkovGrigoriy** [webim/webim-client-sdk-ios#4]
Hello, Could you help me with this, please. My code will have crashed after set nil property in dictionary: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object {
    "history_revision" = "<null>";
} for key ru.webim.WebimClientSDKiOS.visitor.8C6D02FE-2139-44F4-BC64-3823CA05948F'

**Comment by webim** [comment]
Hi!

Thanks for reporting this one! It will be fixed within a new release (version 3.13.0 is coming in a few days).

**Comment by webim** [comment]
This issue must not appear again since version 3.13.0.
