### ISSUE TITLE
Weak reference to SendFileCompletionHandler

### ISSUE THREAD

**Issue by nayzak** [webim/webim-client-sdk-ios#5]
`WebimRequest` has weak reference to `sendFileCompletionHandler`. `MessageStreamImpl.send(file: filename: mimeType: completionHandler:)` creates wrapper around clients completion handler (`SendFileCompletionHandlerWrapper`) and doesn't retain it. So clients completion handler doesn't work when it used with that method.

**Comment by webim** [comment]
Fixed since version 3.22.3.
